#!/bin/bash

# gcloud compute --project=ncbi-sandbox-blast instances create strides-dns-agent --zone=us-east4-b --machine-type=f1-micro --subnet=default --network-tier=PREMIUM --maintenance-policy=MIGRATE --service-account=1008590670571-compute@developer.gserviceaccount.com --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append --image=debian-9-stretch-v20190124 --image-project=debian-cloud --boot-disk-size=10GB --boot-disk-type=pd-standard --boot-disk-device-name=strides-dns-agent --labels=creator=vartanianmh,maintainer=vartanianmh
# sudo dpkg-reconfigure --priority=low unattended-upgrades
# sudo apt install dnsutils less pcregrep

cat <<-EOF | sort -u > hosts
cgsbpubc1.nlm.nih.gov
clinbackc1.nlm.nih.gov
clinbackp1.nlm.nih.gov
clinbackp2.nlm.nih.gov
clinc1.nlm.nih.gov
clindbc1.nlm.nih.gov
clindbc2.nlm.nih.gov
clindbp1.nlm.nih.gov
clindbp2.nlm.nih.gov
clinentryc1.nlm.nih.gov
clinentryc2.nlm.nih.gov
clinentryp1.nlm.nih.gov
clinentryp2.nlm.nih.gov
clinentryp3.nlm.nih.gov
clinftpp.nlm.nih.gov
clinicalreferences.nlm.nih.gov
clinicaltrials-nccs.nlm.nih.gov
clinicaltrials.gov
clinprsqa.nlm.nih.gov
clinrptp1.nlm.nih.gov
clinsparec3.nlm.nih.gov
clinsrvp1.nlm.nih.gov
clinsrvp10.nlm.nih.gov
clinsrvp2.nlm.nih.gov
clinsrvp3.nlm.nih.gov
clinsrvp4.nlm.nih.gov
clinsrvp5.nlm.nih.gov
clinsrvp7.nlm.nih.gov
clinsrvp8.nlm.nih.gov
clinsrvp9.nlm.nih.gov
clint1.nlm.nih.gov
clint2.nlm.nih.gov
clint3.nlm.nih.gov
clint4.nlm.nih.gov
clintest-nccs.nlm.nih.gov
clinwebc1.nlm.nih.gov
clinwebc2.nlm.nih.gov
clinwebc3.nlm.nih.gov
clinwebp1.nlm.nih.gov
clinwebp2.nlm.nih.gov
clinwebp3.nlm.nih.gov
ctgov.nlm.nih.gov
dns1-ncbi.ncbi.nlm.nih.gov
essie4.nlm.nih.gov
fasp1-v250.be-md.ncbi.nlm.nih.gov
fasp21-1.be-md.ncbi.nlm.nih.gov
faspgap11-1.be-md.ncbi.nlm.nih.gov
faspgap12-1.be-md.ncbi.nlm.nih.gov
faspgap21-1.be-md.ncbi.nlm.nih.gov
faspgap22-1.be-md.ncbi.nlm.nih.gov
ftp.ncbi.nih.gov
ftp.ncbi.nlm.nih.gov
ftp.wip.ncbi.nlm.nih.gov
ftp11-1.be-md.ncbi.nlm.nih.gov
ftp12-1.be-md.ncbi.nlm.nih.gov
ftp13-1.be-md.ncbi.nlm.nih.gov
ftp21-1.be-md.ncbi.nlm.nih.gov
ftp22-1.be-md.ncbi.nlm.nih.gov
gap-download.be-md.ncbi.nlm.nih.gov
gap-download.wip.ncbi.nlm.nih.gov
gap-sview.ncbi.nlm.nih.gov
genewebc3.nlm.nih.gov
ghr-nccs.nlm.nih.gov
ghrwebc1.nlm.nih.gov
ghrwebc2.nlm.nih.gov
ghrwebc3.nlm.nih.gov
ghrwebc4.nlm.nih.gov
git-scm.nlm.nih.gov
hostmaster.nih.gov
ipmi-cgsbpubc1.nlm.nih.gov
ipmi-clinc1.nlm.nih.gov
ipmi-clindbc1.nlm.nih.gov
ipmi-clindbc2.nlm.nih.gov
ipmi-clinentryc1.nlm.nih.gov
ipmi-clinentryc2.nlm.nih.gov
ipmi-clinwebc1.nlm.nih.gov
ipmi-clinwebc2.nlm.nih.gov
ipmi-clinwebc3.nlm.nih.gov
ipmi-genebackc1.nlm.nih.gov
ipmi-geneconc1.nlm.nih.gov
ipmi-genewebc1.nlm.nih.gov
ipmi-genewebc2.nlm.nih.gov
ipmi-genewebc3.nlm.nih.gov
ipmi-lhcnccsecm1.nlm.nih.gov
ipmi-lhcnccsecm2.nlm.nih.gov
ipmi-lhcnccsmnts.nlm.nih.gov
ipmi-lhcnccsssh1.nlm.nih.gov
ipmi-lhcnccsssh2.nlm.nih.gov
ipmi-morc1.nlm.nih.gov
ipmi-morc2.nlm.nih.gov
ipmi-morc3.nlm.nih.gov
ipmi-profwebc1.nlm.nih.gov
ipv6monitor.nlm.nih.gov
jira.nlm.nih.gov
lhce-openi-5.nlm.nih.gov
lhce-openi-backup.nlm.nih.gov
lhcnccsecm.nlm.nih.gov
lhcnccsecm1.nlm.nih.gov
lhcnccsecm2.nlm.nih.gov
lhcnccsipmi1.nlm.nih.gov
lhcnccsmnts.nlm.nih.gov
lhcnccsremote.nlm.nih.gov
lhcnccsssh1.nlm.nih.gov
lhcnccsssh2.nlm.nih.gov
lhcns-nccs.nlm.nih.gov
lhcns1.nlm.nih.gov
lhcns5.nlm.nih.gov
lhcns6.nlm.nih.gov
lhcpub2.nlm.nih.gov
local-abapps.nlm.nih.gov
local-dcms.nlm.nih.gov
local-dlxs.nlm.nih.gov
local-download.nlm.nih.gov
local-fmss.nlm.nih.gov
local-id.nlm.nih.gov
local-iiif.nlm.nih.gov
local-inventory.nlm.nih.gov
local-jira-ext.nlm.nih.gov
local-last.nlm.nih.gov
local-oers.nlm.nih.gov
local-resource.nlm.nih.gov
local-ts.nlm.nih.gov
local-uts.nlm.nih.gov
local-utsldap.nlm.nih.gov
local-utsws.nlm.nih.gov
local-vsac.nlm.nih.gov
local-vsacsrch.nlm.nih.gov
local-www.nlm.nih.gov
local-wwwcf.nlm.nih.gov
mesh.nlm.nih.gov
mlbweb.nlm.nih.gov
mor-nccs-testvip.nlm.nih.gov
morc1.nlm.nih.gov
morc2.nlm.nih.gov
morc3.nlm.nih.gov
newbornscreeningcodes-demo.nlm.nih.gov
newbornscreeningcodes-nccs.nlm.nih.gov
nlm.nih.gov
nlmdnshostmaster.mail.nih.gov
nlmnccsaddc.nlm.nih.gov
ns.nih.gov
old-lhcns5.nlm.nih.gov
openi.nlm.nih.gov
openi.wip.nlm.nih.gov
outreach.nlm.nih.gov
profiles-nccs.nlm.nih.gov
profilesinternal-nccs.nlm.nih.gov
profilestest-nccs.nlm.nih.gov
profwebc1.nlm.nih.gov
profwebc2.nlm.nih.gov
prstest.nlm.nih.gov
psext11-1.be-md.ncbi.nlm.nih.gov
raah.nlm.nih.gov
relais.nlm.nih.gov
sftp.nlm.nih.gov
sfxapp.nlm.nih.gov
sra-download.ncbi.nlm.nih.gov
sra-download.wip.ncbi.nlm.nih.gov
srafiles11-1.be-md.ncbi.nlm.nih.gov
srafiles12-1.be-md.ncbi.nlm.nih.gov
srafiles21-1.be-md.ncbi.nlm.nih.gov
srafiles22-1.be-md.ncbi.nlm.nih.gov
svn.nlm.nih.gov
swap-lhcns6.nlm.nih.gov
systems.ncbi.nlm.nih.gov
testvip.nlm.nih.gov
toxnet.nlm.nih.gov
toxnet.wip.nlm.nih.gov
utsreport.nlm.nih.gov
vsearch.nlm.nih.gov
vsearch.wip.nlm.nih.gov
waivercountries.nlm.nih.gov
wiki.nlm.nih.gov
www.ncbi.nlm.nih.gov
www.wip.ncbi.nlm.nih.gov
wwwns.nlm.nih.gov
EOF


date
DATE=$(date "+%Y%m%d") #_%H%M%S

exit

for host in $(sort -u hosts); do
    for ns in $(sort -u nameservers.txt); do
        mkdir -p "results/$ns"
        dig "@$ns" "$host" > "results/$ns/$host.$DATE.dig"
        sleep 0.2
    done
done
date
