# Not to be used directly!
# Include into a sub-dir Makefile after defining format-specifying
# make variables PREFIX and CPREFIX, e.g.:
#
# PREFIX := aws
# CPREFIX := AWS
#

include ../Makefile.set

all: cmn $(PREFIX)
	@echo "done"

cmn:
	$(MAKE) -C ../common

test: acc_test

clean: $(PREFIX)_clean

mkdir:
	@ mkdir -p $(BINDIR) $(OBJDIR)

.phony: all test clean mkdir common_prof prof

#################################################
# tools to produce

FWD_TOOL = $(BINDIR)/$(PREFIX)2jsn
REV_TOOL = $(BINDIR)/jsn2$(PREFIX)

#################################################
# stand alone parser

$(CPREFIX)2JSN_CMN_SRC += \
	$(PREFIX)_parser.cpp \
	$(PREFIX)_scanner.cpp \
	$(CPREFIX)_Interface.cpp

.precious: $(PREFIX)_scanner.cpp $(PREFIX)_scanner.hpp $(PREFIX)_parser.cpp $(PREFIX)_parser.hpp

$(CPREFIX)2JSN_SRC = $($(CPREFIX)2JSN_CMN_SRC) $(PREFIX)2jsn.cpp
JSN2$(CPREFIX)_SRC = $($(CPREFIX)2JSN_CMN_SRC) jsn2$(PREFIX).cpp

$(CPREFIX)2JSN_DBG_OBJ = $(addprefix $(OBJDIR)/,$(subst .cpp,.dbg.o,$($(CPREFIX)2JSN_SRC)))
$(CPREFIX)2JSN_REL_OBJ = $(addprefix $(OBJDIR)/,$(subst .cpp,.rel.o,$($(CPREFIX)2JSN_SRC)))
$(CPREFIX)2JSN_PROF_OBJ = $(addprefix $(OBJDIR)/,$(subst .cpp,.prof.o,$($(CPREFIX)2JSN_SRC)))

JSN2$(CPREFIX)_DBG_OBJ = $(addprefix $(OBJDIR)/,$(subst .cpp,.dbg.o,$(JSN2$(CPREFIX)_SRC)))
JSN2$(CPREFIX)_REL_OBJ = $(addprefix $(OBJDIR)/,$(subst .cpp,.rel.o,$(JSN2$(CPREFIX)_SRC)))
JSN2$(CPREFIX)_PROF_OBJ = $(addprefix $(OBJDIR)/,$(subst .cpp,.prof.o,$(JSN2$(CPREFIX)_SRC)))

$(OBJDIR)/$(PREFIX)_parser.dbg.o:  	$(OBJDIR)/$(PREFIX)_scanner.dbg.o
$(OBJDIR)/$(PREFIX)_parser.rel.o:  	$(OBJDIR)/$(PREFIX)_scanner.rel.o
$(OBJDIR)/$(PREFIX)_parser.prof.o:  $(OBJDIR)/$(PREFIX)_scanner.prof.o

$(OBJDIR)/$(CPREFIX)_Interface.dbg.o $(OBJDIR)/$(CPREFIX)_Interface.rel.o $(OBJDIR)/$(CPREFIX)_Interface.prof.o : $(PREFIX)_parser.hpp
$(PREFIX)_parser.hpp : $(PREFIX)_parser.cpp

$(FWD_TOOL)-dbg: $($(CPREFIX)2JSN_DBG_OBJ) $(DBG_TOOL_OBJ)
	$(LD) -o $@ $^ $(COMMON_DBG_OBJ) $(LDFLAGS)

$(FWD_TOOL)-rel: $($(CPREFIX)2JSN_REL_OBJ) $(REL_TOOL_OBJ)
	$(LD) -o $@ $^ $(COMMON_REL_OBJ) $(LDFLAGS)

$(FWD_TOOL)-prof: $($(CPREFIX)2JSN_PROF_OBJ) $(PROF_TOOL_OBJ)
	$(LD) -o $@ $^ $(COMMON_PROF_OBJ) $(GPROFFLAGS) $(LDFLAGS)

$(REV_TOOL)-dbg: $(JSN2$(CPREFIX)_DBG_OBJ) $(DBG_TOOL_OBJ)
	$(LD) -o $@ $^ $(COMMON_DBG_OBJ) $(LDFLAGS)

$(REV_TOOL)-rel: $(JSN2$(CPREFIX)_REL_OBJ) $(REL_TOOL_OBJ)
	$(LD) -o $@ $^ $(COMMON_REL_OBJ) $(LDFLAGS)

$(REV_TOOL)-prof: $(JSN2$(CPREFIX)_PROF_OBJ) $(PROF_TOOL_OBJ)
	$(LD) -o $@ $^ $(COMMON_PROF_OBJ) $(GPROFFLAGS) $(LDFLAGS)

$(PREFIX): mkdir $(FWD_TOOL)-dbg $(FWD_TOOL)-rel $(REV_TOOL)-dbg $(REV_TOOL)-rel

prof: mkdir common_prof $(FWD_TOOL)-prof $(REV_TOOL)-prof

common_prof :
	$(MAKE) -C ../common prof

$(PREFIX)_TEST_PARSE_SRC    += $($(CPREFIX)2JSN_CMN_SRC) $(PREFIX)_test_parse.cpp
$(PREFIX)_TEST_FLEX_SRC     += $(PREFIX)_test_flex.cpp $(PREFIX)_scanner.cpp
$(PREFIX)_TEST_REVERSE_SRC  += $(PREFIX)_test_reverse.cpp $(PREFIX)_parser.cpp $(PREFIX)_scanner.cpp

$(PREFIX)_TEST_PARSE_DBG_OBJ = $(addprefix $(OBJDIR)/,$(subst .cpp,.dbg.o,$($(PREFIX)_TEST_PARSE_SRC)))
$(PREFIX)_TEST_PARSE_REL_OBJ = $(addprefix $(OBJDIR)/,$(subst .cpp,.rel.o,$($(PREFIX)_TEST_PARSE_SRC)))

$(PREFIX)_TEST_FLEX_DBG_OBJ = $(addprefix $(OBJDIR)/,$(subst .cpp,.dbg.o,$($(PREFIX)_TEST_FLEX_SRC)))
$(PREFIX)_TEST_FLEX_REL_OBJ = $(addprefix $(OBJDIR)/,$(subst .cpp,.rel.o,$($(PREFIX)_TEST_FLEX_SRC)))

$(PREFIX)_TEST_REVERSE_DBG_OBJ = $(addprefix $(OBJDIR)/,$(subst .cpp,.dbg.o,$($(PREFIX)_TEST_REVERSE_SRC)))
$(PREFIX)_TEST_REVERSE_REL_OBJ = $(addprefix $(OBJDIR)/,$(subst .cpp,.rel.o,$($(PREFIX)_TEST_REVERSE_SRC)))

$(BINDIR)/$(PREFIX)_test_parse-dbg: $($(PREFIX)_TEST_PARSE_DBG_OBJ)
	$(LD) -o $@ $^  $(COMMON_DBG_OBJ) -lgtest $(LDFLAGS)

$(BINDIR)/$(PREFIX)_test_parse-rel: $($(PREFIX)_TEST_PARSE_REL_OBJ)
	$(LD) -o $@ $^  $(COMMON_REL_OBJ) -lgtest $(LDFLAGS)

$(BINDIR)/$(PREFIX)_test_flex-dbg: $($(PREFIX)_TEST_FLEX_DBG_OBJ)
	$(LD) -o $@ $^ -lgtest -lpthread

$(BINDIR)/$(PREFIX)_test_flex-rel: $($(PREFIX)_TEST_FLEX_REL_OBJ)
	$(LD) -o $@ $^ -lgtest -lpthread

#$(BINDIR)/$(PREFIX)_test_reverse-dbg: $(CPREFIX)_Interface.cpp
$(BINDIR)/$(PREFIX)_test_reverse-dbg: $($(PREFIX)_TEST_REVERSE_DBG_OBJ)
	$(LD) -o $@ $^ $(COMMON_DBG_OBJ) -lgtest $(LDFLAGS)

#$(BINDIR)/$(PREFIX)_test_reverse-rel: $(CPREFIX)_Interface.cpp
$(BINDIR)/$(PREFIX)_test_reverse-rel: $($(PREFIX)_TEST_REVERSE_REL_OBJ)
	$(LD) -o $@ $^ $(COMMON_REL_OBJ) -lgtest $(LDFLAGS)

unittest_parse: $(PREFIX) flex_test $(BINDIR)/$(PREFIX)_test_parse-dbg $(BINDIR)/$(PREFIX)_test_parse-rel
	$(BINDIR)/$(PREFIX)_test_parse-dbg
	$(BINDIR)/$(PREFIX)_test_parse-rel

flex_test: $(PREFIX) $(BINDIR)/$(PREFIX)_test_flex-dbg $(BINDIR)/$(PREFIX)_test_flex-rel
	$(BINDIR)/$(PREFIX)_test_flex-dbg
	$(BINDIR)/$(PREFIX)_test_flex-rel

unittest_reverse: $(PREFIX) $(BINDIR)/$(PREFIX)_test_reverse-dbg $(BINDIR)/$(PREFIX)_test_reverse-rel
	$(BINDIR)/$(PREFIX)_test_reverse-dbg
	$(BINDIR)/$(PREFIX)_test_reverse-rel

.PHONY: $(PREFIX) prof unittest_parse flex_test unittest_reverse

ALL_OBJ = $($(CPREFIX)2JSN_DBG_OBJ) $($(CPREFIX)2JSN_REL_OBJ) $($(CPREFIX)2JSN_PROF_OBJ) \
$(JSN2$(CPREFIX)_DBG_OBJ) $(JSN2$(CPREFIX)_REL_OBJ) $(JSN2$(CPREFIX)_PROF_OBJ) \
$($(PREFIX)_TEST_PARSE_DBG_OBJ) $($(PREFIX)_TEST_PARSE_REL_OBJ) \
$($(PREFIX)_TEST_FLEX_DBG_OBJ) $($(PREFIX)_TEST_FLEX_REL_OBJ) \
$($(PREFIX)_TEST_REVERSE_DBG_OBJ) $($(PREFIX)_TEST_REVERSE_REL_OBJ)

ALL_D = $(subst .o,.d, $(ALL_OBJ) )

-include $(ALL_D)

$(PREFIX)_clean:
	@ rm -rf $(ALL_OBJ) $(ALL_D) $(BINDIR)/$(PREFIX)* $(BINDIR)/jsn2$(PREFIX)*
	@ rm -rf ./$(PREFIX)_parser.?pp ./$(PREFIX)_scanner.?pp
	@ rm -rf *.output

#################################################
# acceptance

TMP_DIR = actual/tmp

acc_test: all unittest_parse unittest_reverse acctest_parse acctest_reverse
	@ rm -rf actual/$(PREFIX)_*
	@ echo "$(PREFIX) tests done"

acctest_parse: all
	#
	@ ../runtestcase.sh ../data/$(PREFIX)_testlines.log $(FWD_TOOL)-dbg $(TMP_DIR)
	@ ../diff_results.sh ../expected/$(PREFIX)_testlines $(TMP_DIR)
	#
	@ echo "$(PREFIX) acctest_parse passed"

JSON1 = ../data/$(PREFIX)_reparse_1.json
JSON1_MT = ../data/$(PREFIX)_reparse_mt.json

RT_JSN = ../data/$(PREFIX)_roundtrip.json
RT_ORIG1_DIR = actual/rt_orig1
RT_JSN_DIR = actual/rt_json
RT_ORIG2_DIR = actual/rt_orig2

acctest_reverse: all
	#
	@ ../runtestcase.sh $(JSON1) $(REV_TOOL)-dbg $(TMP_DIR)
	@ ../diff_results.sh ../expected/$(PREFIX)_rev_testlines $(TMP_DIR)
	#
	# multi-threaded
	@ ../runtestcase.sh $(JSON1_MT) $(REV_TOOL)-dbg $(TMP_DIR)
	@ ../diff_results.sh ../expected/$(PREFIX)_reparse_mt $(TMP_DIR)
	#
	# round trip
	# reparse 1
	@ ../runtestcase.sh $(RT_JSN) $(REV_TOOL)-dbg $(RT_ORIG1_DIR)
	# forward parse the original format
	@ ../runtestcase.sh $(RT_ORIG1_DIR)/out.good.$(PREFIX) $(FWD_TOOL)-dbg $(RT_JSN_DIR)
	# reparse 2, compare the output of 2 reparses
	@ ../runtestcase.sh $(RT_JSN_DIR)/out.good.jsonl $(REV_TOOL)-dbg $(RT_ORIG2_DIR)
	@ ../diff_results.sh $(RT_ORIG1_DIR) $(RT_ORIG2_DIR)
	#
	@ echo "$(PREFIX) acctest_reverse passed"

.PHONY: acc_test acctest_parse acctest_reverse

#################################################
# valgrind

VG_OPTIONS := --leak-check=full --error-exitcode=1
VG_BUILD = dbg
#VG_BUILD = rel

vg_fwd : mkdir $(FWD_TOOL)-$(VG_BUILD) $(BINDIR)/$(PREFIX)_test_flex-$(VG_BUILD) $(BINDIR)/$(PREFIX)_test_parse-$(VG_BUILD)
	valgrind $(VG_OPTIONS) $(BINDIR)/$(PREFIX)_test_flex-$(VG_BUILD)
	valgrind $(VG_OPTIONS) $(BINDIR)/$(PREFIX)_test_parse-$(VG_BUILD)
	cat ../data/$(PREFIX)_testlines.log | valgrind $(VG_OPTIONS) $(FWD_TOOL)-$(VG_BUILD) $(TMP_DIR)

vg_rev : mkdir $(REV_TOOL)-$(VG_BUILD) $(BINDIR)/$(PREFIX)_test_reverse-$(VG_BUILD)
	valgrind $(VG_OPTIONS) $(BINDIR)/$(PREFIX)_test_reverse-$(VG_BUILD)
	cat ../data/$(PREFIX)_reparse_1.json | valgrind $(VG_OPTIONS) $(REV_TOOL)-$(VG_BUILD) $(TMP_DIR)

vg : vg_fwd vg_rev

.PHONY: vg_fwd vg_rev vg

#-------------------------------------------------------------------------------
# fuzz testing

clean_fuzz:
	rm -rf fuzz/

FUZZ_SRC = \
	$($(CPREFIX)2JSN_CMN_SRC) \
	$(PREFIX)_fuzz.cpp

FUZZ_OBJ = \
	$(addprefix $(OBJDIR)/,$(subst .cpp,.fuzz.o,$(FUZZ_SRC)))

$(BINDIR)/$(PREFIX)-fuzz: $(PREFIX) $(FUZZ_OBJ)
	clang++ -g -o $@ $(FUZZ_OBJ) $(FUZZ_OPT) $(COMMON_DBG_OBJ) $(LDFLAGS)

#$(CPREFIX)_FUZZ_DICT ?= -dict=fuzz/$(PREFIX)-dict

fuzz: $(BINDIR)/$(PREFIX)-fuzz
	 mkdir -p fuzz/$(PREFIX)-corpus fuzz/$(PREFIX)-seeds
	 cp ../data/$(PREFIX)_testlines.log fuzz/$(PREFIX)-seeds/
	 $^ $($(CPREFIX)_FUZZ_DICT) -runs=$(FUZZ_RUNS) fuzz/$(PREFIX)-corpus fuzz/$(PREFIX)-seeds

.phony: clean_fuzz fuzz
