# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import logmon_pb2 as logmon__pb2


class MessageTransportStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendLogMessage = channel.unary_unary(
                '/logmon.MessageTransport/SendLogMessage',
                request_serializer=logmon__pb2.LogMessage.SerializeToString,
                response_deserializer=logmon__pb2.TransportResult.FromString,
                )


class MessageTransportServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendLogMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessageTransportServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendLogMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendLogMessage,
                    request_deserializer=logmon__pb2.LogMessage.FromString,
                    response_serializer=logmon__pb2.TransportResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'logmon.MessageTransport', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MessageTransport(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendLogMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/logmon.MessageTransport/SendLogMessage',
            logmon__pb2.LogMessage.SerializeToString,
            logmon__pb2.TransportResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
