# this makefile does not build anything, it is here to run tests

test :
	python3 test_api_file_log.py
	python3 test_file_watcher.py

#depends on bq having the right auth: 'python3 test_api_http_log.py'

phony: test
